substances['Datura'] = {
    img: 'datura.png',
    info: 'Datura is known as powerful and dangerous deliriant, used for shamanic and medical purposes, as well as poisons.',
    addictionLevel: 0,
    special: false,
    power: 7,
    unlockPoints: 0,
    walkDelay: false,
    worksOnMethod: ['eat', 'drink', 'smoke'],
    stats: {
        stimulant: false,
        sedative: false,
        hallucinogic: true,
        delirant: true,
        dissociative: false,
        depressant: false,
    },
    cssEffects: {
        from: {
            1: '',
            2: '',
            3: 'margin-left: -10px;',
            4: 'margin-left: -30px;',
            5: 'margin-left: -80px;',
        },
        to: {
            1: '',
            2: '',
            3: 'margin-left: 10px;',
            4: 'margin-left: 30px;',
            5: 'margin-left: 80px;',
        }
    },
    cssFilterEffects: {
        from: {
            1: 'grayscale(0%) blur(0px) brightness(100%)',
            2: 'grayscale(0%) blur(0px) brightness(100%)',
            3: 'grayscale(0%) blur(0px) brightness(100%)',
            4: 'grayscale(0%) blur(0px) brightness(100%)',
            5: 'grayscale(0%) blur(0px) brightness(100%)',
        },
        to: {
            1: 'grayscale(40%) blur(0px) brightness(50%)',
            2: 'grayscale(50%) blur(1px) brightness(40%)',
            3: 'grayscale(60%) blur(1px) brightness(30%)',
            4: 'grayscale(70%) blur(2px) brightness(20%)',
            5: 'grayscale(90%) blur(3px) brightness(20%)',
        }
    },
    deepDreamEffect: false,
    deepDreamEffectConfig: {
        1: 0,
        2: 0,
        3: 0,
        4: 0,
        5: 0,
    },
    mirrorEffect: true,
    mirrorEffectActiveInPower: 2,
    delirant: true,
    highDelirantEffectActiveInPower: 3, 
    whiteNoise: true,
    whiteNoiseEffectActiveInPower: 5,
    starsEffect: false,
    starsEffectActiveInPower: 0,
    dmtEffect: false,
    dmtEffectActiveInPower: 0,
}