substances['DMT'] = {
    img: 'dmt.png',
    info: 'DMT is known for its unique ability to produce short-lived but intense visionary states and complete hallucinations.',
    addictionLevel: 0,
    power: 1,
    unlockPoints: 0,
    walkDelay: false,
    worksOnMethod: ['eat', 'drink', 'smoke'],
    stats: {
        stimulant: false,
        sedative: true,
        hallucinogic: true,
        delirant: false,
        dissociative: false,
        depressant: false,
    },
    cssEffects: {
        from: {
            1: '',
            2: '',
            3: '',
            4: '',
            5: '',
        },
        to: {
            1: '',
            2: '',
            3: '',
            4: '',
            5: '',
        }
    },
    cssFilterEffects: {
        from: {
            1: 'saturate(3) contrast(150%)',
            2: 'saturate(4) contrast(150%)',
            3: 'saturate(5) hue-rotate(0deg) contrast(200%)',
            4: 'saturate(6) hue-rotate(0deg) contrast(250%)',
            5: '',
        },
        to: {
            1: 'saturate(1) contrast(100%)',
            2: 'saturate(1) contrast(100%)',
            3: 'saturate(1) hue-rotate(360deg) contrast(100%)',
            4: 'saturate(1) hue-rotate(360deg) contrast(100%)',
            5: '',
        }
    },
    deepDreamEffect: true,
    deepDreamEffectConfig: {
        1: 0,
        2: 3,
        3: 5,
        4: 5,
        5: 0,
    },
    mirrorEffect: true,
    mirrorEffectActiveInPower: 1,
    delirant: false,
    highDelirantEffectActiveInPower: 0,
    whiteNoise: false,
    whiteNoiseEffectActiveInPower: 0,
    starsEffect: true,
    starsEffectActiveInPower: 3,
    dmtEffect: true,
    dmtEffectActiveInPower: 5,
}